# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a558a79993a45676e660515f9b36019581724fe6ef3854dfab8782d95ff0f434bdd2983d1f9dbf999f2acc1561c333921c2a8213cafec6225b296f5fa5022ebb

test:
  secret_key_base: 71102dd6e23c8232712f9e0974aa5eeba8c51fcdab0ceb7b6c62a8d0c48f704568c8306cfc205396399c2fd0dd64ab53a68cdffc87f4017599b8ed6451821633

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
